export const movies=[{rating:"3",
  title:"Spider",
  descripton:"Inception is a 2010 psychological science fiction action film[3] written and directed by Christopher Nolan",
  img:"https://m.media-amazon.com/images/M/MV5BMmY4OGRmNWMtNmIyNS00YWQ5LWJmMGUtMDI3MWRlMmQ0ZDQzL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"},
  {rating:"3",
  title:"The one",
  descripton:"Inception is a 2010 psychological science fiction action film[3] written and directed by Christopher Nolan",
  img:"https://m.media-amazon.com/images/M/MV5BNzY4YmUzMDAtMDYyZS00MTBmLWEzZDAtOGY3MDE2YjJkMGUxL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg"},
  {rating:"5",
  title:"Titanic",
  descripton:"Inception is a 1997 psychological science fiction action film[3] written and directed by Christopher Nolan",
  img:"https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg"},
  {rating:"4",
  title:"Contagion",
  descripton:"Inception is a 2012 psychological science fiction action film[3] written and directed by Christopher Nolan",
  img:"https://m.media-amazon.com/images/M/MV5BMTY3MDk5MDc3OV5BMl5BanBnXkFtZTcwNzAyNTg0Ng@@._V1_SX300.jpg"},
  {rating:"4",
  title:"Saw",
  descripton:"Two strangers, who awaken in a room with no recollection of how they got there, soon discover they're pawns in a deadly game perpetrated by a notorious serial killer",
  img:"https://m.media-amazon.com/images/M/MV5BMjE4MDYzNDE1OV5BMl5BanBnXkFtZTcwNDY2OTYwNA@@._V1_SX300.jpg"},
  {rating:"5",
  title:"The stranger",
  descripton:"Crime, Drama, Film-Noir, Mystery, Thriller",
  img:"https://m.media-amazon.com/images/M/MV5BMTExMDAzMDM0NzZeQTJeQWpwZ15BbWU3MDk3ODIzNzQ@._V1_SX300.jpg"},
  {rating:"2",
  title:"Snoopy Come Home",
  descripton:"When Snoopy receives a letter from a girl named Lila, who's in a hospital, he goes on a journey with Woodstock to see her.",
  img:"https://m.media-amazon.com/images/M/MV5BMjRhYjVjMWEtMDVlMy00ZTUyLWI3NTgtMDZlMzI4Nzk2NzgxXkEyXkFqcGdeQXVyNTkxMzEwMzU@._V1_SX300.jpg"},
  {rating:"5",
  title:"Tom and Jerry",
  descripton:"A weekly Saturday (later Sunday) Morning repackaged compilation with new wraparounds featuring two Tom and Jerry cartoons sandwiching other MGM animated theatrical shorts.",
  img:"https://m.media-amazon.com/images/M/MV5BMjA3NzUwNjQwOF5BMl5BanBnXkFtZTcwMTcwNTYyMQ@@._V1_SX300.jpg"},
  {rating:"1",
  title:"Batman",
  descripton:"Action, Adventure,Director",
  img:"https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg"} ]